---
title: "Class 08"
author: "Ella O'Neall"
date: "2026-09-21"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
    code_download: TRUE
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Illustrating the httr2 functions

```{r slide8}
httr2::request("https://data.cincinnati-oh.gov/resource/rvmt-pkmq.json") |>
  httr2::req_url_query("$limit" = 5) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON()
```
# FRED Example

```{r FRED}
Sys.getenv("FRED_API_KEY")   # shows the key, so: Console only
usethis::use_git_ignore(".Renviron")

ohio_jobs =  
  httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
    httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json"
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON()

  
# we saw that the data is in observations
ohio_df = ohio_jobs$observations
  
dplyr::glimpse(ohio_jobs)
  
# another approach to filter the dates would be:
  ohio_df |>
    # overwrite the date col and convert to date (from chr)
    dplyr::mutate(date = lubridate::ymd(date)) |>
    # bc it is a date, we can do logical checks on it and keep dates from sep 01, 2026
    dplyr::filter(date >= "2026-09-01") -> ohio_df_sept_2026
```

## USA JOBS

```{r usajobs}
usa_jobs_data = 
httr2::request("https://data.usajobs.gov/api/search") |>
  httr2::req_url_query(Keyword = "Data Analyst", ResultsPerPage = 500) |>
  httr2::req_headers(
    Host = "data.usajobs.gov",
    "User-Agent" = "oneallej@miamioh.edu",
    "Authorization-Key" = Sys.getenv("USAJOBS_API_KEY")
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON(flatten = TRUE) -> usa_jobs_data

usa_jobs_df = usa_jobs_data$SearchResult$SearchResultItems

jobs_small = usa_jobs_df |>
  dplyr::select(
    title = MatchedObjectDescriptor.PositionTitle,
    department = MatchedObjectDescriptor.DepartmentName,
    location = MatchedObjectDescriptor.PositionLocationDisplay
  )

## Easy way -- since we looked for data analyst as a key word 
nrow(jobs_small)
# q 2
table(jobs_small$department) |> sort(decreasing = T)
jobs_small |> dplyr::count(department) |>
  dplyr::arrange(dplyr::desc(n)) |> head(3)

## The harder way (but being literal)
jobs_small |> dplyr::filter(title == 'Data Analyst')

## The harder way (without being literal)
# Jesse <-  Data analyst or analytics side by side
index_data_analyst = jobs_small$title |>
  stringr::str_detect("Data Analyst|Data Analytics")

# given that this is a true or false type result
# true rows will be kept
#  , noting means keep all columns 
count_jesse_standard = jobs_small[index_data_analyst, ]

#jobs_small |> dplyr::count(department |>
                             #dplyr::arrange())
```

