---
title: 'Class 10: Web scraping'
author: "Ella O'Neall"
date: "2026-09-28"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
    code_download: TRUE
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Robotstxt
The code chunk below will show the output from the [robotstxt package]() for the ISA course bulletin available at:
<https://bulletin.miamioh.edu/courses-instruction/isa/index.html>

```{r robotstxt}
robotstxt::paths_allowed(paths = "/courses-instruction/isa/", domain = "bulletin.miamioh.edu", bot = "*")
```
## robotstxt demo

From the chunk below, we are allowed to scrape the [MU Football Wiki Page](https://en.wikipedia.org/wiki/Miami_RedHawks_football)

```{r wiki}
robotstxt::paths_allowed(paths = "/wiki/Miami_RedHawks_football", domain = "en.wikipedia.org", bot = "*")
```
```{r linkedin}
robotstxt::paths_allowed(paths = "/jobs/", domain = "www.linkedin.com", bot = "*")
```
```{r indeed}
robotstxt::paths_allowed(paths = "/jobs", domain = "www.indeed.com", bot = "*")

robotstxt::paths_allowed(paths = "/viewjob", domain = "www.indeed.com", bot = "*")
```

## `rvest` demo: ISA course bulletin

```{r rvest_demo}
isa_page_in_r = rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/")

# extract the titles
# if all titles look the same on the page, it means that they have the same tag/class, which would allow you to extract them in one step

# we got the selector below by:
## [a] highlighted the course
## [b] right clicked and selected inspect
## [c] i found the part that was flushed containing the title
## [d] right clicked and copied the selector
## [e] i saw that the output from the code below just got me the 24th course so i dropped the `:nth-child(24)`
isa_page_in_r |>
  rvest::html_elements("#sc_sccoursedescs > div > p.courseblocktitle > strong") |>
  rvest::html_text2() -> isa_titles

# course descriptions
# ccs selector obtained using the selector gadget
isa_page_in_r |>
  rvest::html_element(".courseblockdesc") |>
  rvest::html_text2() -> isa_descs

isa_df = data.frame(
  title = isa_titles, description = isa_descs
)
```


